export interface ResolverConfig {
    CONTEST_COLOR: string;
    CONTEST_CAPTION: string;
    BASE_URL_WS: string;

    SCOREBOARD_ROW_TRANSITION_TIME: number; // ms
    SCOREBOARD_SCROLL_INTERVAL: number; // ms

    GLOBAL_DEFAULT_FONT_FAMILY: string; // css-property
    GLOBAL_DEFAULT_FONT_SIZE: string; // css-property
    GLOBAL_DEFAULT_FONT_WEIGHT: number; // css-property
    GLOBAL_DEFAULT_FONT_WEIGHT_BOLD: number; // css-property
    GLOBAL_DEFAULT_FONT: string;
    GLOBAL_BACKGROUND_COLOR: string;
    GLOBAL_TEXT_COLOR: string;
    GLOBAL_BORDER_RADIUS: string;

    VERDICT_OK: string;
    VERDICT_NOK: string;
    VERDICT_UNKNOWN: string;

    VERDICT_LABEL_FONT_SIZE: string;
    VERDICT_CELL_TRANSITION_TIME: number;
    VERDICT_CELL_BRODER_RADIUS: string;

    SCOREBOARD_RESOLVED_ROWS_BELOW: number;
    SCOREBOARD_CHOSEN_ROW_COLOR: string;
    SCOREBOARD_BACKGROUND_COLOR: string;
    SCOREBOARD_BORDER_RADIUS: string;
    SCOREBOARD_TEXT_COLOR: string;
    SCOREBOARD_CAPTION_FONT_SIZE: string; // css value
    SCOREBOARD_HEADER_BACKGROUND_COLOR: string;
    SCOREBOARD_HEADER_DIVIDER_COLOR: string;
    SCOREBOARD_HEADER_FONT_SIZE: string;
    SCOREBOARD_HEADER_FONT_WEIGHT: number;
    SCOREBOARD_HEADER_HEIGHT: number;
    SCOREBOARD_ROWS_DIVIDER_COLOR: string;
    SCOREBOARD_ROW_HEIGHT: number; // px
    SCOREBOARD_ROW_PADDING: number; // px
    SCOREBOARD_BETWEEN_HEADER_PADDING: number; // px
    SCOREBOARD_ROW_FONT_SIZE: string;
    SCOREBOARD_TABLE_ROW_FONT_WEIGHT: number;

    SCOREBOARD_CELL_PLACE_SIZE: string;
    SCOREBOARD_CELL_TEAMNAME_SIZE: string;
    SCOREBOARD_CELL_TEAMNANE_ALIGN: string;
    SCOREBOARD_CELL_POINTS_SIZE: string;
    SCOREBOARD_CELL_POINTS_ALIGN: string;
    SCOREBOARD_CELL_PENALTY_SIZE: string;
    SCOREBOARD_CELL_PENALTY_ALIGN: string;

    SCOREBOARD_NORMAL_NAME: string;
    SCOREBOARD_OPTIMISTIC_NAME: string;
    SCOREBOARD_PESSIMISTIC_NAME: string;
    SCOREBOARD_UNDEFINED_NAME: string;
    SCOREBOARD_STANDINGS_NAME: string;

    SCOREBOARD_GAP: string;
    SCOREBOARD_PADDING_TOP: string;
    SCOREBOARD_PADDING_RIGHT: string;
    SCOREBOARD_PADDING_LEFT: string;
    SCOREBOARD_HEADER_PADDING_TOP: string;
    SCOREBOARD_CELL_PADDING: string;
    SCOREBOARD_HEADER_BORDER_RADIUS_TOP_LEFT: string;
    SCOREBOARD_HEADER_BORDER_RADIUS_TOP_RIGHT: string;
}
